import type { Metadata } from "next";
import Link from "next/link";
import { Shell } from "@/components/site-shell";
import { Reveal } from "@/components/reveal";

export const metadata: Metadata = { title: "Official Speaker & Media Kit — Dr. Khanh Nguyen", description: "Official bios, brand assets, headshots, speaking topics, interview preparation, credentials, and booking details for Dr. Khanh Nguyen." };

const shortBio = "Dr. Khanh Nguyen is a longevity and regenerative medicine expert, founder of Austin Regenerative Therapy, and SSRP Fellow. She helps audiences look beyond symptoms to understand what drives cellular decline—and how foundational health, responsible innovation, and the right therapeutic sequence can help people function better for longer.";
const mediumBio = "Dr. Khanh Nguyen is a longevity and regenerative medicine expert with more than 20 years of hospital-based critical care experience. After navigating her own autoimmune illness and caring for a son with a rare neurological condition, she shifted from asking only what the diagnosis was to asking what caused the cell to struggle in the first place. As founder of Austin Regenerative Therapy, she begins with the individual’s biology and foundational health, then thoughtfully sequences therapies ranging from hormone optimization and peptides to plasma exchange and cellular medicine. Dr. Nguyen is an SSRP Fellow, educator, and sought-after voice on the science, ethics, and future of living better for longer.";
const fullBio = [
  "Dr. Khanh Nguyen is a physician, longevity and regenerative medicine expert, educator, and founder of Austin Regenerative Therapy. With more than 20 years in hospital-based critical care, she brings the rigor of acute medicine to one of health care’s fastest-moving fields.",
  "Her path into regenerative medicine is deeply personal. After overcoming an autoimmune illness and caring for a son with a rare neurological condition, Dr. Nguyen became what she calls “patient number one.” She began looking beyond crisis-driven care and asking what caused the cell to struggle in the first place. Today, she starts with each person’s biology, history, goals, and foundational health before determining which therapies belong in the plan—and in what sequence.",
  "Born in Vietnam, Dr. Nguyen escaped the country by boat at 13 and rebuilt her life in the United States. She studied biology at the University of Southern California, earned her medical degree from Rush Medical College, and completed fellowship training in critical care. She is board-certified in internal medicine, an SSRP Fellow and faculty member, and an ISSCA educator. On stage and in the media, she translates complex science into candid, useful conversations about what regenerative medicine can—and cannot—do.",
];
const topics = [
  ["What Makes the Cell Fail?", "Follow the question that moved Dr. Nguyen from crisis medicine to root-cause cellular care—and learn why better health decisions begin by looking upstream."],
  ["Plasma Exchange & Healthspan", "Understand the differences among plasma-based protocols, where evidence is strongest, and which questions responsible patients and practitioners should ask."],
  ["Peptides & Personalized Medicine", "See how biomarkers, pathways, and individual goals can shape a more precise and responsible approach to peptide therapy."],
  ["The Right Therapy, in the Right Sequence", "See why the patient’s biology, foundational health, and goals must come before the product—and why timing can determine whether an intervention succeeds."],
  ["Hormones, Women & Longevity", "Explore how hormonal change affects energy, sexual health, cognition, and the experience of aging across every decade."],
  ["From Burnout to Reinvention", "Recognize when a successful life is no longer sustainable—and how to rebuild work, health, and identity with intention."],
];
const questions = [
  "What does regenerative medicine actually mean—and where does the hype begin?", "Which Hallmarks of Aging can clinicians meaningfully address today?", "How do Young Plasma Exchange and therapeutic plasma exchange differ?", "What should patients understand before considering peptides, exosomes, or cellular therapies?", "How do you personalize a longevity plan without chasing every new intervention?", "What did critical care teach you about prevention and healthspan?", "How did your own health experience change the way you practice medicine?", "Where do ethics and patient safety fit in a field moving this quickly?", "What do most people misunderstand about aging—and what should they focus on instead?", "For listeners ready to explore whether regenerative care is right for them, where can they learn more and schedule a discovery call with your team?",
];
const appearances = [["The Dr. Pompa Podcast","Podcast guest","2026"],["Ben Greenfield Life","Two-time podcast guest","2025–2026"],["Longevity Optimization","Guest with Kayla Barnes-Lentz","2026"],["ISSCA Peptide World Conference","Speaker · Lima, Peru","2026"],["Peptide World Congress","SSRP faculty panel","2026"],["ISSCA International Regenerative Medicine Conference","Speaker · Lima, Peru","2025"]];

export default function MediaKit() { return <Shell><main className="press-room">
  <section className="press-room-hero"><img src="/dr-khanh-media-hero.jpg" alt="Dr. Khanh Nguyen speaking on stage about regenerative medicine"/><div className="press-room-hero-shade"/><div className="press-room-hero-content"><p className="eyebrow light">Official speaker & media kit</p><h1>Dr. Khanh Nguyen<br/><em>on stage, on air & in the conversation.</em></h1><p>The official source for approved bios, brand assets, speaking topics, interview preparation, and booking details.</p><div className="button-row"><a className="button light" href="/dr-khanh-nguyen-speaker-media-kit.pdf" download>Download Complete Kit</a><Link className="text-link light" href="/contact?type=speaking">Book Dr. Nguyen →</Link></div></div><div className="press-room-proof"><span>Physician</span><span>SSRP Fellow</span><span>International Speaker</span><span>Regenerative Medicine Expert</span></div></section>
  <nav className="kit-jump" aria-label="Media kit sections"><a href="#assets">Brand Assets</a><a href="#bios">Bios</a><a href="#topics">Speaking</a><a href="#appearances">Appearances</a><a href="#interview">Interview Prep</a><a href="#planning">Booking</a></nav>

  <section className="section kit-assets" id="assets"><div className="kit-intro-grid"><div><p className="eyebrow">Brand assets</p><h2>A consistent presence,<br/><em>wherever she appears.</em></h2></div><p>Approved files and visual standards for event programs, podcast artwork, press coverage, social promotion, and partner communications.</p></div><div className="brand-board">
    <Reveal className="brand-logo-panel"><div className="brand-logo-light"><img src="/dr-khanh-nguyen-logo.png" alt="Dr. Khanh Nguyen official logo"/></div><div className="brand-logo-dark"><img src="/dr-khanh-nguyen-logo.png" alt="Dr. Khanh Nguyen logo in reverse"/></div><a className="brand-download" href="/dr-khanh-nguyen-logo.png" download><span>Official logo · transparent PNG</span><b>Download ↘</b></a></Reveal>
    <Reveal className="brand-rules" delay={.08}><div><p className="eyebrow">Color palette</p><div className="swatches"><span style={{background:"#155e56"}}><b>Regenerative Teal</b><small>#155E56</small></span><span style={{background:"#b8874a"}}><b>Warm Gold</b><small>#B8874A</small></span><span style={{background:"#faf7f2",color:"#1c1b19"}}><b>Editorial Cream</b><small>#FAF7F2</small></span><span style={{background:"#1c1b19"}}><b>Ink</b><small>#1C1B19</small></span></div></div><div className="type-spec"><p className="eyebrow">Typography</p><span className="type-serif">Editorial serif</span><span className="type-sans">CLEAN SANS-SERIF</span></div><div className="usage-note"><p className="eyebrow">Usage</p><p>Preserve clear space around the logo. Do not stretch, recolor, outline, crop, or place it over a visually busy area. Use approved photography without facial retouching or filters.</p></div></Reveal>
  </div></section>

  <section className="kit-photography"><div className="kit-photo stage"><img src="/dr-khanh-stage-square.jpg" alt="Dr. Khanh Nguyen delivering a keynote on stage"/><span>On-stage keynote · square</span></div><div className="kit-photo portrait"><img src="/dr-khanh-nguyen.jpg" alt="Dr. Khanh Nguyen portrait"/><span>Official portrait</span></div><div className="kit-photo interview"><img src="/dr-khanh-pompa-interview-clean.jpg" alt="Dr. Khanh Nguyen in conversation with Dr. Pompa"/><span>Podcast & interview · landscape</span></div><div className="photo-actions"><p className="eyebrow light">Approved photography</p><h2>Authority in every setting.</h2><p>High-resolution, media-ready files for print and digital use.</p><div><a href="/dr-khanh-stage-square.jpg" download>Download square stage image ↘</a><a href="/dr-khanh-nguyen.jpg" download>Download portrait ↘</a><a href="/dr-khanh-pompa-interview-clean.jpg" download>Download interview image ↘</a></div></div></section>

  <section className="section kit-bios-redesign" id="bios"><div className="kit-intro-grid"><div><p className="eyebrow">Approved biographies</p><h2>Choose the right length.<br/><em>Keep the story intact.</em></h2></div><p>Prepared for event programs, podcast notes, press profiles, introductions, and digital listings.</p></div><div className="bio-ledger"><Reveal className="bio-entry short"><header><span>01</span><h3>Short bio</h3><small>47 words</small></header><p>{shortBio}</p></Reveal><Reveal className="bio-entry medium"><header><span>02</span><h3>Medium bio</h3><small>109 words</small></header><p>{mediumBio}</p></Reveal><Reveal className="bio-entry full"><header><span>03</span><h3>Full bio</h3><small>For features & introductions</small></header><div>{fullBio.map(p=><p key={p}>{p}</p>)}</div></Reveal></div></section>

  <section className="section kit-topics-redesign" id="topics"><div className="kit-intro-grid light"><div><p className="eyebrow light">Speaking platform</p><h2>Science made clear.<br/><em>Possibility made responsible.</em></h2></div><p>Each topic can be tailored to a keynote, panel, fireside conversation, clinical audience, leadership audience, or media interview.</p></div><div className="topic-editorial-grid">{topics.map(([title,takeaway],i)=><Reveal className="topic-editorial" key={title} delay={(i%3)*.05}><span>0{i+1}</span><h3>{title}</h3><p><b>Audience takeaway</b>{takeaway}</p></Reveal>)}</div><div className="credentials-strip"><b>Credentials</b><span>Board-certified Internal Medicine</span><span>Fellowship-trained Critical Care</span><span>SSRP Fellow & Faculty</span><span>ISSCA Faculty</span></div></section>

  <section className="section kit-appearances" id="appearances"><div className="kit-intro-grid"><div><p className="eyebrow">Selected appearances</p><h2>Trusted with the<br/><em>important conversations.</em></h2></div><Link className="text-link" href="/media">Watch & explore all media →</Link></div><div className="appearance-feature"><img src="/dr-khanh-pompa-interview-clean.jpg" alt="Dr. Khanh Nguyen in conversation with Dr. Pompa"/><div><p className="eyebrow light">Featured conversation</p><h3>The Dr. Pompa Podcast</h3><p>Plasma exchange, cellular medicine, peptides, and what it means to pursue longevity responsibly.</p></div></div><div className="engagement-list">{appearances.map((a,i)=><Reveal className="engagement-row" key={a[0]} delay={(i%3)*.05}><span>{String(i+1).padStart(2,"0")}</span><div><h3>{a[0]}</h3><p>{a[1]}</p></div><time>{a[2]}</time></Reveal>)}</div></section>

  <section className="section kit-interview-redesign" id="interview"><div className="interview-heading"><p className="eyebrow light">Interview preparation</p><h2>Ten questions designed to create a conversation—not a commercial.</h2><p>Question ten gives Dr. Nguyen a natural, audience-first bridge to the next step.</p></div><ol>{questions.map((q,i)=><li key={q} className={i===9?"conversion-question":""}><span>{String(i+1).padStart(2,"0")}</span><p>{q}</p>{i===9&&<b>Listener pathway · Website + discovery call</b>}</li>)}</ol></section>

  <section className="section kit-stage-planning" id="planning"><div className="stage-intro-card"><p className="eyebrow">Stage introduction</p><h2>Ready to read as written.</h2><blockquote>“Our guest is a physician, longevity and regenerative medicine expert, and founder of Austin Regenerative Therapy. After more than 20 years in hospital-based critical care, Dr. Khanh Nguyen turned her focus to proactive, cellular-level medicine. She is an SSRP Fellow and faculty member, an ISSCA educator, and a trusted voice on peptides, plasma exchange, cellular therapies, hormones, and the science of healthspan. Please welcome Dr. Khanh Nguyen.”</blockquote></div><div className="planning-card"><p className="eyebrow light">Booking & production</p><h2>A smooth event starts before the stage.</h2><div><article><b>Formats</b><p>Keynotes, panels, fireside conversations, podcasts, media appearances, and virtual sessions. Typical talks adapt from 20–60 minutes.</p></article><article><b>Production</b><p>Wireless lavalier or headset microphone, presentation connection, confidence monitor for timed programs, and an on-site AV check.</p></article><article><b>Travel</b><p>Based in Austin, Texas. Final travel, accommodations, transportation, and scheduling are confirmed during booking.</p></article></div><Link className="button light" href="/contact?type=speaking">Start a Booking Inquiry</Link></div></section>
</main></Shell>; }
